### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by Recillah-Khamala** [Recillah-Khamala/Cook-Partner#9]
Hello Code Reviewer,

This project is being implemented by 2 people, @Doheera-kosi and myself (@Recillah-Khamala ). The link to our GitHub repository is https://github.com/Recillah-Khamala/Cook-Partner, and the link to our project is https://github.com/Recillah-Khamala/Cook-Partner/projects/1.

**Comment by Abenezer-Tilahun** [comment]
Hi @Recillah-Khamala  @Doheera-kosi  , 

Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ Good Job for Providing information about the number of people in your group.


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

- [ ] Kindly make sure that you provide the correct link to the GitHub project, which supposed to this [link](https://github.com/Recillah-Khamala/Cook-Partner/projects/1) and also kindly make sure that all the project requirement are in To-Do list activity.


_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Recillah-Khamala** [comment]
Hello Code Reviewer,

This project is being implemented by 2 people, @Doheera-kosi and myself (@Recillah-Khamala ). The link to our GitHub repository is https://github.com/Recillah-Khamala/Cook-Partner, and the link to our project is https://github.com/Recillah-Khamala/Cook-Partner/projects/1.
I have implemented the change request to put all the cards on the to-do list.

**Comment by m05e5** [comment]
**Hi @Recillah-Khamala @Doheera-kosi 

You did great. Your kanban board is complete!  There is nothing else to say other than... its time to start coding :shipit: 
Congratulations! 🎉 
![CleverScornfulBuffalo-size_restricted](https://user-images.githubusercontent.com/37901469/208869296-5ca9f6cc-a1b5-48fd-bd59-78fd83b35471.gif)

## Highlights
✔️ Clean kanban board

## Optional suggestions



_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_**m05e5**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._**
